version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit:1.4.4
    container_name: "fluent-bit"
    ports:
      - "5170:5170"
    volumes: 
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./parsers.conf:/parsers.conf"
    networks:
      - "fluent-bit-net"

networks:
  fluent-bit-net:
    external: false
    name: "fluent-bit-net"  