version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit:1.4.4
    container_name: "fluent-bit"
    ports:
      - "1883:1883"    
    volumes: 
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
    networks:
      - "fluent-bit-net"
    depends_on:
      - "kafka"           

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"
    networks:
      - "fluent-bit-net"

  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
    networks:
      - "fluent-bit-net"
    depends_on:
      - "zookeeper" 

networks:
  fluent-bit-net:
    external: false
    name: "fluent-bit-net"      
